name: .NET Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest  # .NET Framework requires Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages (if any)
      run: nuget restore  # Only needed if you have NuGet packages

    - name: Build Debug configuration
      run: msbuild CyberAiOpenChat.csproj /p:Configuration=Debug /p:Platform=AnyCPU

    - name: Build Release configuration
      run: msbuild CyberAiOpenChat.csproj /p:Configuration=Release /p:Platform=AnyCPU

    - name: Run tests (if any)
      run: |
        if exist "**\*Tests.dll" (
          vstest.console.exe **\*Tests.dll
        ) else (
          echo "No test DLLs found"
        )
